include:
  - ../mongodb/docker-compose.yaml
  - ../kafka/docker-compose.yaml

services:
  simulator_prod:
    build: 
      context: .
      target: final
      dockerfile: Dockerfile.prod
    container_name: simulator_prod
    depends_on:
      - mongo-replica
      - kafka
    environment:
      - MONGO_URI=mongodb://vehicle-tracking:vehicle-tracking@mongo-replica:27017/routes?authSource=admin&directConnection=true
      - KAFKA_BROKER=kafka:9092
      - KAFKA_ROUTE_TOPIC=route
      - KAFKA_FREIGHT_TOPIC=freight
      - KAFKA_SIMULATION_TOPIC=simulation
      - KAFKA_GROUP_ID=route-group

  # simulator:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: simulator
  #   depends_on:
  #     - mongo-replica
  #     - kafka
  #   volumes:
  #     - .:/app
  #   environment:
  #     - MONGO_URI=mongodb://vehicle-tracking:vehicle-tracking@mongo-replica:27017/routes?authSource=admin&directConnection=true
  #     - KAFKA_BROKER=kafka:9092
  #     - KAFKA_ROUTE_TOPIC=route
  #     - KAFKA_FREIGHT_TOPIC=freight
  #     - KAFKA_SIMULATION_TOPIC=simulation
  #     - KAFKA_GROUP_ID=route-group